create extension if not exists vector with schema extensions;

create table if not exists public.memories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  title text not null,
  body text not null,
  user_phrasing text,
  memory_type text not null default 'note',
  tags text[] not null default '{}',
  source text not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists public.memory_vectors (
  memory_id uuid primary key references public.memories(id) on delete cascade,
  embedding extensions.vector(1536) not null,
  created_at timestamptz not null default now()
);

create index if not exists memories_user_created_at_idx
  on public.memories (user_id, created_at desc);

create table if not exists public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  title text not null default 'New chat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  user_id uuid not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  message_order bigint generated by default as identity,
  created_at timestamptz not null default now()
);

create index if not exists chat_sessions_user_updated_at_idx
  on public.chat_sessions (user_id, updated_at desc);

create index if not exists chat_messages_session_order_idx
  on public.chat_messages (session_id, message_order);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_chat_sessions_updated_at on public.chat_sessions;
create trigger set_chat_sessions_updated_at
  before update on public.chat_sessions
  for each row
  execute function public.set_updated_at();

create or replace function public.touch_chat_session()
returns trigger
language plpgsql
as $$
begin
  update public.chat_sessions
  set updated_at = now()
  where id = new.session_id;

  return new;
end;
$$;

drop trigger if exists touch_chat_session_after_message on public.chat_messages;
create trigger touch_chat_session_after_message
  after insert on public.chat_messages
  for each row
  execute function public.touch_chat_session();

create or replace function public.match_memories(
  query_embedding extensions.vector(1536),
  match_threshold double precision,
  match_count integer
)
returns table (
  id uuid,
  user_id uuid,
  title text,
  body text,
  memory_type text,
  created_at timestamptz,
  similarity double precision
)
language sql
stable
as $$
  select
    memories.id,
    memories.user_id,
    memories.title,
    memories.body,
    memories.memory_type,
    memories.created_at,
    1 - (memory_vectors.embedding <=> query_embedding) as similarity
  from public.memory_vectors
  join public.memories on memories.id = memory_vectors.memory_id
  where 1 - (memory_vectors.embedding <=> query_embedding) > match_threshold
  order by memory_vectors.embedding <=> query_embedding
  limit match_count;
$$;

grant usage on schema public to anon, authenticated;
grant all on table public.memories to anon, authenticated;
grant all on table public.memory_vectors to anon, authenticated;
grant all on table public.chat_sessions to anon, authenticated;
grant all on table public.chat_messages to anon, authenticated;
grant usage, select on sequence public.chat_messages_message_order_seq to anon, authenticated;
grant execute on function public.match_memories(extensions.vector, double precision, integer)
  to anon, authenticated;

-- The current app does not authenticate users; it sends a hard-coded user_id
-- from the client. Keep RLS disabled until the app is updated to use auth.
alter table public.memories disable row level security;
alter table public.memory_vectors disable row level security;
alter table public.chat_sessions disable row level security;
alter table public.chat_messages disable row level security;
